/**
 * The blocks.
 *
 * The PHPUnit suite already proves the render callbacks return the same markup
 * the shortcodes return, so repeating that here would buy nothing. What only a
 * browser can answer is whether the *built* JavaScript works: `build/` is
 * generated by bin/build and is not in the repository, so every assertion below
 * is also an assertion that the build ran and produced something a browser can
 * load.
 *
 * Two things are worth a browser and nothing else here is:
 *
 * * the editor script loads and registers both blocks -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else;
 * * a post holding each block renders it on the front end, which exercises the
 *   registration against the name that was actually written into post_content.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
const {
	PERMISSION,
	listing,
	resetSite,
	seedDownloads,
	uniqueName,
} = require( './helpers.js' );

/** The two blocks this plugin registers. */
const DOWNLOAD_BLOCK = 'wp-downloadmanager/download';
const PAGE_BLOCK = 'wp-downloadmanager/page-download';

test.describe( 'The blocks', () => {
	let files;
	let ids;

	test.beforeAll( async ( { requestUtils } ) => {
		await requestUtils.deleteAllPosts();
	} );

	test.beforeEach( async () => {
		resetSite();

		files = {
			manual: {
				name: uniqueName( 'Block Manual' ),
				file: 'e2e-block-manual.txt',
				contents: 'a manual',
				description: 'The manual, for everybody.',
				category: 1,
				permission: PERMISSION.everyone,
			},
		};

		ids = seedDownloads( files );
	} );

	test.afterAll( async () => {
		resetSite();
	} );

	test.describe( 'in the editor', () => {
		test( 'both blocks are registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and neither
			// name is here -- which is the failure this whole file exists for.
			expect( names ).toContain( DOWNLOAD_BLOCK );
			expect( names ).toContain( PAGE_BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'downloadmanager/download' );

			// Three shortcodes, two blocks. The plural spelling of the listing
			// shortcode is the same callback under a second tag, so it gets no
			// block -- and a block registered here would be a second name to
			// support in post_content forever.
			expect( names ).not.toContain(
				'wp-downloadmanager/page-downloads',
			);
		} );

		test( 'the download block previews the file it is given', async ( {
			admin,
			editor,
		} ) => {
			await admin.createNewPost();
			await editor.insertBlock( {
				name: DOWNLOAD_BLOCK,
				attributes: { id: String( ids.manual ) },
			} );

			// The preview is core's ServerSideRender, which posts the attributes
			// to /wp/v2/block-renderer/ and draws what the front end would draw.
			// Seeing the file here is what proves the block earns no REST route
			// of its own.
			await expect(
				editor.canvas.getByText( files.manual.name ),
			).toBeVisible();
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a post holding the download block renders the file', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'A download in a block',
				content: `<!-- wp:${ DOWNLOAD_BLOCK } {"id":"${ ids.manual }"} /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );

			await expect( listing( page ) ).toContainText( files.manual.name );
		} );

		test( 'the block and the shortcode render the same file', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'Both entry points at once',
				content: `<!-- wp:${ DOWNLOAD_BLOCK } {"id":"${ ids.manual }"} /-->\n\n[download id="${ ids.manual }"]`,
				status: 'publish',
			} );

			await page.goto( post.link );

			// Two renders of one file, so the name appears twice -- which is the
			// point: adding a block did not stop the shortcode working on the
			// same page.
			await expect(
				page.getByText( files.manual.name ),
			).toHaveCount( 2 );
		} );

		test( 'a post holding the listing block renders the listing', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await requestUtils.createPost( {
				title: 'A listing in a block',
				content: `<!-- wp:${ PAGE_BLOCK } /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );

			await expect( listing( page ) ).toContainText( files.manual.name );
		} );
	} );
} );
